[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/pi/printer_data/comms/klippy.sock

[authorization]
trusted_clients:
    127.0.0.1
    10.0.0.0/8
    127.0.0.0/8
    172.16.0.0/12
    192.168.0.0/16
    FE80::/10
    ::1/128
cors_domains:
    *.lan
    *.local
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz

[octoprint_compat]

[file_manager]
enable_object_processing: True
queue_gcode_uploads: True

[job_queue]
load_on_startup: True

[history]

[power Ender_5_Kalico]
type: tasmota
address: pp-w162-e5.lan
off_when_shutdown: True
on_when_job_queued: True
locked_while_printing: True
bound_services: klipper
#restart_klipper_when_powered: True
#restart_delay: 1

[spoolman]
server: http://localhost:7912
#   URL to the Spoolman instance. This parameter must be provided.
sync_rate: 5
#   The interval, in seconds, between sync requests with the
#   Spoolman server.  The default is 5.

[update_manager]
channel: dev
refresh_interval: 168
enable_auto_refresh: True

[update_manager klipper]
channel: stable

[update_manager fluidd]
path: /home/pi/fluidd
repo: fluidd-core/fluidd
channel: stable
type: web
persistent_files:
    config.json

[update_manager fluidd-config]
managed_services: klipper
origin: https://github.com/fluidd-core/fluidd-config.git
path: /home/pi/fluidd-config
primary_branch: master
type: git_repo

[update_manager mainsail]
path: /home/pi/mainsail
repo: mainsail-crew/mainsail
channel: stable
type: web
persistent_files:
    config.json

[update_manager Spoolman]
type: zip
channel: stable
repo: Donkie/Spoolman
path: ~/Spoolman
virtualenv: .venv
requirements: requirements.txt
persistent_files:
    .venv
    .env
managed_services: Spoolman

[update_manager klipperfleet]
type: zip
path: ~/KlipperFleet
repo: JohnBaumb/KlipperFleet
channel: beta
managed_services: klipperfleet
virtualenv: venv
requirements: backend/requirements.txt
system_dependencies: install_scripts/system-dependencies.json


[update_manager katapult]
type: git_repo
path: /home/pi/katapult
origin: https://github.com/Arksine/katapult.git
primary_branch: master
is_system_service: False
[update_manager klipper-backup]
type: git_repo
path: ~/klipper-backup
origin: https://github.com/Staubgeborener/klipper-backup.git
managed_services: moonraker
primary_branch: main